Repository TodaysFail/TodaysFail-FE, pull requests merged in 2023-04, with the labels that each got.

#89 feat: 로그인 페이지 엔터 키로 시작하기 구현
  src/pages/LoginPage/LoginPage.jsx
Labels: feat

#87 fix: 회원가입 페이지 비밀번호 확인 및 엔터 submit 수정
  src/pages/SignUpPage/SignUpPage.jsx
Labels: feat, fix

#93 feat/fix: 회원가입 폼 유효성 검사 진행 타이밍 수정 및 capslock 알림 구현
  src/components/signUp/SignUpForm.jsx
  src/pages/SignUpPage/SignUpPage.jsx
Labels: feat, fix

#100 refactor: 코드 개선 및 에러 핸들링
  .eslintrc.json
  src/components/receipt/ReceiptShareContainer.jsx
  src/components/signUp/SignUpForm.jsx
  src/pages/SignUpPage/SignUpPage.jsx
Labels: refactor

#103 feat: 메인 페이지 배너 추가
  src/assets/coffee1.svg
  src/assets/coffee2.svg
  src/components/myPage/EventBanner.jsx
  src/components/myPage/Profile.jsx
  src/pages/MyPage/MyPage.jsx
Labels: feat

#105 docs: readme update
  README.md
Labels: docs
